### ISSUE TITLE
Word offsets (TokenRange) doesn't always work for Arabic

### ISSUE THREAD

**Issue by wasiahmad** [ufal/udpipe#123]
TokenRange seems not always working. I have tried it for the Arabic language and surprisingly, for every word it is not produced. For most work, it is produced, but in a few cases, it doesn't. Wondering why that happens? And what is the solution?

**Comment by jwijffels** [comment]
That happens when a single token is composed of several syntactic words. E.g. in German 'Wir gehen zum kino' (we are going to the cinema), zum is decomposed of zu and dem. In the UDPipe output you can only see the tokenranges for zum, not for zu and dem as they were not in the text but derived from the word.

Example using the R wrapper:

```
library(udpipe)
x <- udpipe("Wir gehen zum Kino", "german-gsd", tokenizer = "tokenizer=ranges")
x[, c("token", "token_id", "start", "end", "misc")]
  token token_id start end                             misc
1   Wir        1     1   3                   TokenRange=0:3
2 gehen        2     5   9                   TokenRange=4:9
3   zum      3-4    11  13                 TokenRange=10:13
4    zu        3    NA  NA                             <NA>
5   dem        4    NA  NA                             <NA>
6  Kino        5    15  18 SpacesAfter=\\n|TokenRange=14:18
```

**Comment by wasiahmad** [comment]
So, what is the solution? What should I do? Should I just skip the words for which I do not have TokenRange?

**Comment by foxik** [comment]
Thanks for the explanation -- that is exactly the reason. UD distinguishes _tokens_ and _words_ (https://universaldependencies.org/u/overview/tokenization.html) -- while tokens are subsequences of the input sequence, words might not be part of the input, and so only _tokens_ get a `TokenRange`.

**Comment by foxik** [comment]
It depends on what you want. Maybe you only want to keep the tokens -- many systems expect that only tokens are annotated. In that case you need to "merge" all words belonging to a single token "together". That is of course problematic (what POS should `zum` have in German?), but at least some approximation can be made (and this is not a specific problem of UDPipe -- all systems have to somehow deal with the fact that many languages "combines" words into tokens).

Note that in UDPipe 3 (yes, 2 is not out yet :-) there will be the possibility of automatically joining words into tokens, so that only tokens will remain. But in the meantime you might need to do it manually in Arabic.

**Comment by foxik** [comment]
Closing, but feel free to reopen if required.

**Comment by wasiahmad** [comment]
What I am doing? I am trying to tokenize the paragraphs for Question Answering on the MLQA dataset. Ref: https://github.com/facebookresearch/MLQA

I need POS tags, DepRels, and head information. So, what kind of approximation do you suggest? 
I am not an expert, so any kind of suggestion would be appreciated.

**Comment by foxik** [comment]
I am not saying merging is ideal, but sometimes you may need all information "grounded" into the original text. Considera portion from Arabic UD training data:
```
1-2	وفي	_	_	_	_	_	_	_	_
1	و	وَ	CCONJ	C---------	_	0	root	0:root	Vform=وَ|Gloss=and|Root=wa|Translit=wa|LTranslit=wa
2	في	فِي	ADP	P---------	AdpType=Prep	3	case	3:case	Vform=فِي|Gloss=in|Root=fI|Translit=fī|LTranslit=fī
```
The first token is composed of two words, and all POS/Features/DepRels/Head information are available for the two words, not the token. You however would like to have the information available for the token -- a trivial possibility is to take the information from the first word and "copy" it to the first token instead (and you need to take care to "reroute" dependency edges which originally lead to word `2` to word `1`).

Alternatively you could take not the first word, but the "more informative" one (maybe prefer VERBs to other POS tags etc), or even merge the information (POS could be `CCONJ+ADP`, lemma could be a concatenation of the two lemmas etc.). Nothing is ideal, of course.

The other possibility is to give up on tokens and use words instead; when you in the end decide which words are part of the answer, you could find out the original token range by looking at the tokens which gave rise to the selected words.
