### ISSUE TITLE
question on compatibility 1.2.0 and 1.2.1-devel

### ISSUE THREAD

**Issue by jwijffels** [ufal/udpipe#136]
with the R package, I'm still running UDPipe 1.2.0, I'm planning to upgrade to 1.2.1-devel in order to have the segment_size and learning_rate_final parameters for tokenizer training

Just a question which I can check myself of course when trying out the different versions and models I have locally but do model constructed with 1.2.0 work similarly under 1.2.1-devel and give same results?

**Comment by foxik** [comment]
Forward compatibility of models should be guaranteed for same major versions, so the models trained in 1.2.0 should work without change in all 1.* versions (of course modulo fixed bugs, which is sometimes not convenient). Nothing should change in 1.2.1, if I recall correctly.

BTW, UDPipe-2 models will be released in a web-service (with the same API as the current one) in ~week, but UDPipe-2 will be only Python (I just had to make the models public because we need them in various projects). The UDPipe 1.2.1 should come out at similar time. The "new" UDPipe (the one in C++, supporting new DL models) will be designated as UDPipe 3 (because we have written several papers about UDPipe 2).

**Comment by jwijffels** [comment]
Thanks for the message.
I'll wait a bit for 1.2.1 then to incorporate these changes (I think the main difference is that  segment_size and learning_rate_final where added to the tokenizer) and publish the updated R package to CRAN. 
And looking forward to UDPipe 3 with the C++ API. :)
