### ISSUE TITLE
Effectively lemmatise list of tokens in Python

### ISSUE THREAD

**Issue by PrimozGodec** [ufal/udpipe#154]
I am writing here since I cannot find a good reference how to lemmatize the list of tokens in Python with UDpipe. Text is already tokenized in the list:

I found out that it can be done with the following piece of code:
```
words = ["houses", "boys", "toys", ...]  # input tokens
model = udpipe.Model.load("path to model")
output_format = udpipe.OutputFormat.newOutputFormat('epe')

lemmas = []
for w in words:
    sentence = udpipe.Sentence()
    sentence.addWord(w)

    model.tag(sentence, __model.DEFAULT)
    output = output_format.writeSentence(sentence)
    lemmas.append(json.loads(output)['nodes'][0]['properties']['lemma'])
```

It does not look optimal since a new sentence is generated for every token, every token is lemmatised separately, and the output is retrieved for every sentence. I can imagine that a more optimal and less time-consuming lemmatization procedure exists. Is there a way how to lemmatize all tokens in one shot?

I tried the following way but it gives different results and is even slower:
```
words = ["houses", "boys", "toys", ...]  # input tokens
model = udpipe.Model.load("path to model")
output_format = udpipe.OutputFormat.newOutputFormat('epe')

sentence = udpipe.Sentence()
for w in words:
    sentence.addWord(w)

model.tag(sentence, __model.DEFAULT)
output = output_format.writeSentence(sentence)
lemmas1 = [n['properties']['lemma'] for n in json.loads(output)['nodes']]
```

**Comment by foxik** [comment]
Hi,

the lemmatizer is mostly meant as "disambiguate using sentence context", so its performance on single words is a bit questionable (i.e., you could come up with a much simpler angorithm if you do not want to consider context; and it is not obvious what UDPipe will do in such situations, given that it was trained on whole sentences).

Anyway, the first approach is the reasonable one; just instead of using the output format, you should be able to do
```python
sentence.words[1].lemma
```
just after the `tag` call. (The index `1` is used because `words[0]` is the technical root required by the dependency trees.)

Cheers.

**Comment by PrimozGodec** [comment]
@foxik Thank you for your response. :)
