### ISSUE TITLE
Help with bulding python

### ISSUE THREAD

**Issue by kiufta** [ufal/udpipe#161]
Hi,

I'm successfully using the udpipe binary. Because I'm on Python 3.10 I would like to build the Python bindings from scratch instead of using pypi. After running
`make PYTHON_INCLUDE=/usr/include/python3.10`
I've got
```
./examples
./ufal
Makefile
pystrings.swg
udpipe_python.cpp
udpipe_python.i
```
But where is the setup.py?

**Comment by foxik** [comment]
Hi,

we still plan to release updated bindings officially, but in a month or two, because we currently have no time to use on UDPipe.

Anyway, the `bindings/python` is just the binding itself; the PyPI package is in `releases/pypi` -- call the `gen.sh` script there (with a single argument, the version of the PyPI package you want to create). That will create `ufal.udpipe` directory with the complete PyPI `ufal.udpipe` package (including the `setup.py`).

Cheers!
