### ISSUE TITLE
Add support for Big-endian platforms?

### ISSUE THREAD

**Issue by barracuda156** [ufal/udpipe#169]
I have been referred to here from respective `R` package: https://github.com/bnosac/udpipe/issues/119

Is it possible to add support for Big-endian platforms?

**Comment by foxik** [comment]
Hi,

I do not plan to do it, because UDPipe is now mostly in maintenance mode, and it would require some non-trivial changes to the code imported from MorphoDiTa (maybe in other places too, the model deserialization is just the first thing that comes to mind). But I am willing to accept patches, if you wanted to do it ;-)

**Comment by barracuda156** [comment]
> Hi,
> 
> I do not plan to do it, because UDPipe is now mostly in maintenance mode, and it would require some non-trivial changes to the code imported from MorphoDiTa (maybe in other places too, the model deserialization is just the first thing that comes to mind). But I am willing to accept patches, if you wanted to do it ;-)

Got it, thanks for a fast reply. This is not my sphere of expertise, unfortunately, so I am afraid I won’t be able to handle non-trivial fixes here…
