### ISSUE TITLE
i run the scrpit udpipe2 server client file but not getting anything please guide me 

### ISSUE THREAD

**Issue by stdntlfe** [ufal/udpipe#174]
[
![image](https://github.com/ufal/udpipe/assets/26096247/3f31b4bb-ad6b-4ef2-b398-a0008d939c22)
](url)
please check aove url for image 

please guide me how i ca run udpipe 2 i my local system

**Comment by foxik** [comment]
Hi,

these issues are meant as reporting bugs/problems in the code, not as getting user support. Therefore, please report an error you are facing; I could not find any neither in the text nor in the image. A good place where to start is to look at the logs (or not logging to the logfile, so that the errors are reported on the console).

**Comment by stdntlfe** [comment]
Hi sir,

Sorry for the inconvenience

I want to run this in my local system but when I run I'm not getting any
output.
Can u please guide me how i can proceed further

Thanks & Regards,
Arvind Kumar

**Comment by foxik** [comment]
The instructions how to proceed are already in my previous message.

Closing now because there is no UDPipe error reported in the issue. If you find some UDPipe-specific error in the logs, feel free to reopen it.
