### ISSUE TITLE
UDPipe on Intel Xeon

### ISSUE THREAD

**Issue by jaakkopasanen** [ufal/udpipe#40]
I tried installing UDPipe on Intel Xeon in Azure and Google Cloud platforms. Install seems to complete successfully but running the code doesn't. I tried installing with pip as well as build from the sources with MODE=release and MODE=debug in current master and in "stable" branch.

When installing with pip, UDPipe crashes with segmentation fault when trying to use it from Python. When building from sources and using with built binary I get error Could not load model.

G++ compiler version if 5.4.0 on Ubuntu 16.04 and using pretrained ud-1.2 models. I also tried to train my own models with the same results.

Has anybody tried building UDPipe on Xeon with any luck?

**Comment by foxik** [comment]
Hi, thanks for the report.

We have been using UDPipe on Xeons since development (but using mostly g++ 4.x).

Which version did you install with pip? Did the crash occur directly after importing `ufal.udpipe` or after loading a model? Also, did you try loading the models using a precompiled binary available from https://github.com/ufal/udpipe/releases)?

**Comment by jaakkopasanen** [comment]
After further investigations I detected that the model file I was using on those cloud Xeon machines was somehow corrupted. After switching to uncorrupted model file the UDPipe started working.

Sorry for useless issue, and thanks for help.

**Comment by foxik** [comment]
Good that it works for you now :-)
