### ISSUE TITLE
cannot start udpipe_server

### ISSUE THREAD

**Issue by jfernal** [ufal/udpipe#56]
./udpipe_server 8080 /root/udpipe-ud-2.0-170801/spanish-ud-2.0-170801.udpipe
Cannot load specified models!

There are any default directory to models?

**Comment by msklvsk** [comment]
The syntax is
`udpipe_server [options] port default_model (rest_id model_file acknowledgements)*`.

Meaning you need to name your model, and come up with some string for acknowledgements. Because you only have one model, just repeat its name for `default_model` like that:
`./udpipe_server 8080 mymodel mymodel /root/udpipe-ud-2.0-170801/spanish-ud-2.0-170801.udpipe 'my acknowledgements'`.

**Comment by foxik** [comment]
Thanks @msklvsk for an exact answer :-)
