### ISSUE TITLE
gcc8 and use of strncpy

### ISSUE THREAD

**Issue by jwijffels** [ufal/udpipe#71]
The CRAN build system is now running gcc8 in r-devel and this reports the following issue at the usage of `strncpy `in `morphodita/tagset_converter/pdt_to_conll2009_tagset_converter.cpp`

```
char pdt_tag[15];
strncpy(pdt_tag, tag.c_str(), 15);

```
**warning: 'char* strncpy(char*, const char*, size_t)' specified bound 15 equals destination size [-Wstringop-truncation]**

Shouldn't the call to strncpy be replaced with `memcpy(pdt_tag, tag.c_str(), 15);`

**Comment by foxik** [comment]
The code itself is perfectly correct, the warning is only about pdt_tag not being null-terminated -- that is expected inside the method. To silence the warning, I changed the size of pdt_tag to 16 so that it is correctly null-terminated (even though I do not need it) in 9aacb3f.

BTW, memcpy might fail because the source tag could be shorter than 15 characters.

**Comment by jwijffels** [comment]
You're right on this. Thank you for the fix!
