### ISSUE TITLE
Error in udp_tokenise_tag_parse(object$model, x, doc_id, tokenizer, tagger,  :    external pointer is not valid

### ISSUE THREAD

**Issue by EricGPTI** [ufal/udpipe#76]
During a training, I was trying to apply the case but received an error. Only in my RStudio, this error is shown.

The code line that, when I execute this line, i received the error that is shown below:
myVariable = udpipe_annotate(myModel, x = myFile$FILE, doc_id = myFile$ID)

So, this error is shows me.

Error in udp_tokenise_tag_parse(object$model, x, doc_id, tokenizer, tagger,  :    external pointer is not valid.

I am using de model "portuguese-br" for interpretation de language.

**Comment by foxik** [comment]
@jwijffels Any idea?

**Comment by jwijffels** [comment]
@EricGPTI Can you redirect questions regarding the R package to https://github.com/bnosac/udpipe 
This issue was raised before by a user and has been answered at https://github.com/bnosac/udpipe/issues/5
It indicates that you either did not have the portuguese-br-ud-2.0-170801.udpipe locally available when you did udpipe_load_model or you tried to load again from a previous save which you should not do but instead use udpipe_load_model. Can you redirect the question to https://github.com/bnosac/udpipe after you have read https://github.com/bnosac/udpipe/issues/5 as it probably should solve your issue when reading that.

**Comment by foxik** [comment]
@jwijffels Thanks!
