### ISSUE TITLE
CoNLL18 Shared Task Baseline UD 2.2 Models

### ISSUE THREAD

**Issue by jwijffels** [ufal/udpipe#79]
Thank you for releasing the CoNLL18 shared task baseline models on lindat.

I have a question on the license of the CoNLL18 Shared Task Baseline UD 2.2 Models.
- The lindat website mentions that the license of these models is Licence Universal Dependencies v2.2,
- This repository which is the backend of the UDPipe website (http://ufal.mff.cuni.cz/udpipe) mentions that these UDPipe  models have been released as CC BY-NC-SA.
I wonder which of the 2 is the appropriate one? On Lindat, also conllu training/test data is shared, are the UDPipe models CC BY-NC-SA and the conllu training/test data under the usual Licence Universal Dependencies v2.2 or are also the UDPipe models released under Licence Universal Dependencies v2.2
Many thanks for your input.

**Comment by foxik** [comment]
The baseline models are under CC BY-NC-SA. The problem is that the LINDAT entry contains not only the baseline models, but also predicted morphology on UD 2.2 training & development data, containing a large copy of UD 2.2. Combining by the fact that individual files in LINDAT entry cannot have different licenses, I used UD 2.2 license to cover the UD 2.2 data in the entry.

We are also preparing the UD 2.2 models with the UDPipe-Future-like architecture (although we might release only UD 2.3, depending on how fast will I overcome the problems); these models will be again released explicitly using CC BY-NC-SA license.

**Comment by jwijffels** [comment]
Clear! Thanks for the input.
