### ISSUE TITLE
"conll18_ud_eval.py": Precision, Recall and F1 the same

### ISSUE THREAD

**Issue by alvelvis** [ufal/udpipe#89]
Hi everyone,
together with the UDPipe 2.2 models I downloaded a while ago, I found the script "conll18_ud_eval.py". After successfully training 2 different versions of Bosque (Portuguese) in UDPipe, I ran that script (--verbose parameter) to compare the 2 golden versions of Bosque with what their models produce through UDPipe (system files). However, the tables always have the same Precision, Recall and F1 numbers. What might be wrong?

Images: https://imgur.com/a/wD805WA

**Comment by arademaker** [comment]
Hi @alvelvis, What do you mean by “2 golden versions of Bosque”?

**Comment by alvelvis** [comment]
Hi @arademaker, I mean an older and a newer version of the golden Bosque, right before and after Luisa and Isabela corrected some of the POS tags in it. We intend to compare if / how much these corrections improve the UDPipe learning process, but we find it strange that Precision, Recall and F1 numbers are exactly the same in all features but the three last ones (as we can see in the pictures)...

**Comment by martinpopel** [comment]
> the tables always have the same Precision, Recall and F1 numbers. What might be wrong?

Nothing is wrong.
If the tokenization is fully correct and all word boundaries are correctly predicted (which is the case in your two tables based on the 100% scores in the "Words" row), then (by definition) Precision=Recall for metrics UPOS, XPOS, UFeats, AllTags, Lemmas, UAS and LAS.
If Precision=Recall, then by definition also the F1 is the same number.

Metrics CLAS, MLAS and BLEX are computed on "content words" only, i.e. words with a deprel in the set of predefined "content relations". If there is a word with a content deprel according to the gold annotation but non-content deprel according to the system annotation (or vice versa), it may happen that Precision is different than Recall (even if word tokenization is fully correct).

For details, see the definition of all the metrics, as described in the [CoNLL2018 Shared task](http://universaldependencies.org/conll18/evaluation.html) and in the [evaluation script source code](https://github.com/ufal/conll2018/blob/master/evaluation_script/conll18_ud_eval.py#L454-L472) (note the `filter_fn=lambda w: w.is_content_deprel` parameter).

BTW: you can use `conll18_ud_eval.py -c` to print counts instead of percentages, so you detect even small differences in scores which would be hidden by rounding the scores to two decimal places.

**Comment by huberemanuel** [comment]
Just adding a resource for future readers: https://simonhessner.de/why-are-precision-recall-and-f1-score-equal-when-using-micro-averaging-in-a-multi-class-problem/

Formally, what is being calculated is the micro-averaging precision and recall.

**Comment by alvelvis** [comment]
Awesome, @huberemanuel ! Thanks a lot.
